/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 adidas.gltf --transform
Author: 3Digify (https://sketchfab.com/3digify)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scanned-adidas-sports-shoe-17f21b0a2515455f96ad194ad5be9142
Title: Scanned Adidas Sports Shoe
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/adidas-transformed.glb')
  return (
    <group {...props} dispose={null} >
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-0.33, -0.17, -0.11]}>
          <mesh geometry={nodes.Object_2.geometry} material={materials.Textured} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Textured} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/adidas-transformed.glb')
